env:
  productCatalogServiceAddr: "productcatalogservice:3550"
  shippingServiceAddr: "shippingservice:50051"
  paymentServiceAddr: "paymentservice:50051"
  emailServiceAddr: "emailservice:5000"
  currencyServiceAddr: "currencyservice:7000"
  cartServiceAddr: "cartservice:7070"
  checkoutServiceAddr: "checkoutservice:5050"
  AdServiceAddr: "adservice:9555"
  recommendationServiceAddr: "recommendationservice:8080"
  redisAddr: "redis-cart:6379"
  jaegerServiceAddr: "jaeger-collector:14268"

emailService:
  terminationGracePeriodSeconds: 5
  image:
    repository: gcr.io/google-samples/microservices-demo/emailservice
    tag: v0.1.0
    pullPolicy: IfNotPresent
  ports:
    containerPort: 8080
  healthChecks:
    readinessProbe:
      periodSeconds: 5
      exec:
        probeBinary: "/bin/grpc_health_probe"
        probeAddr: "-addr=:8080"
    livenessProbe:
      periodSeconds: 5
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:8080"]
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  service:
    type: ClusterIP
    name: grpc
    port: 5000