apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: server
        image: {{ printf "%s:%s" .Values.checkoutService.image.repository .Values.checkoutService.image.tag }}
        ports:
        - containerPort: {{ .Values.checkoutService.ports.containerPort }}
        readinessProbe:
          exec:
            command: {{ printf "[%q, \"-addr=:%v\"]" .Values.checkoutService.healthChecks.readinessProbe.exec.probeBinaryPath .Values.emailService.healthChecks.readinessProbe.exec.probePort }}
        livenessProbe:
          exec:
            command: {{ printf "[%q, \"-addr=:%v\"]" .Values.checkoutService.healthChecks.livenessProbe.exec.probeBinaryPath .Values.emailService.healthChecks.livenessProbe.exec.probePort }}
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: {{ .Values.env.productCatalogServiceAddr }}
        - name: SHIPPING_SERVICE_ADDR
          value: {{ .Values.env.shippingServiceAddr }}
        - name: PAYMENT_SERVICE_ADDR
          value: {{ .Values.env.paymentServiceAddr }}
        - name: EMAIL_SERVICE_ADDR
          value: {{ .Values.env.emailServiceAddr }}
        - name: CURRENCY_SERVICE_ADDR
          value: {{ .Values.env.currencyServiceAddr }}
        - name: CART_SERVICE_ADDR
          value: {{ .Values.env.cartServiceAddr }}
        # - name: JAEGER_SERVICE_ADDR
        #   value: {{ .Values.env.jaegerServiceAddr }}
        resources:
          requests:
            cpu: {{ .Values.checkoutService.resources.requests.cpu }}
            memory: {{ .Values.checkoutService.resources.requests.memory }}
          limits:
            cpu: {{ .Values.checkoutService.resources.limits.cpu }}
            memory: {{ .Values.checkoutService.resources.limits.memory }}
