apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      terminationGracePeriodSeconds: 5
      #terminationGracePeriodSeconds: {{ .Values.emailService.terminationGracePeriodSeconds }}
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.1.0
        #image: {{ printf "%s:%s" .Values.emailService.image.repository .Values.emailService.image.tag }}
        ports:
        - containerPort: 8080
        #- containerPort: {{ .Values.emailService.ports.containerPort }}
        readinessProbe:
          periodSeconds: 5
          #periodSeconds: {{ .Values.emailService.healthChecks.readinessProbe.periodSeconds }}
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
            #command: {{ .Values.emailService.healthChecks.readinessProbe.exec.command }}
        livenessProbe:
          periodSeconds: 5
          #periodSeconds: {{ .Values.emailService.healthChecks.livenessProbe.periodSeconds }}
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
            #command: {{ .Values.emailService.healthChecks.livenessProbe.exec.command }}
        resources:
          #requests:
          #  cpu: {{ .Values.cartService.resources.requests.cpu }}
          #  memory: {{ .Values.cartService.resources.requests.memory }}
          #limits:
          #  cpu: {{ .Values.cartService.resources.limits.cpu }}
          #  memory: {{ .Values.cartService.resources.limits.memory }}