apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      terminationGracePeriodSeconds: {{ .Values.emailService.terminationGracePeriodSeconds }}
      containers:
      - name: server
        image: {{ printf "%s:%s" .Values.emailService.image.repository .Values.emailService.image.tag }}
        ports:
        - containerPort: {{ .Values.emailService.ports.containerPort }}
        readinessProbe:
          periodSeconds: {{ .Values.emailService.healthChecks.readinessProbe.periodSeconds }}
          exec:
            command: {{ printf "[%q, \"-addr=:%v\"]" .Values.emailService.healthChecks.readinessProbe.exec.probeBinaryPath .Values.emailService.healthChecks.readinessProbe.exec.probePort }}
        livenessProbe:
          periodSeconds: {{ .Values.emailService.healthChecks.livenessProbe.periodSeconds }}
          exec:
            command: {{ printf "[%q, \"-addr=:%v\"]" .Values.emailService.healthChecks.livenessProbe.exec.probeBinaryPath .Values.emailService.healthChecks.livenessProbe.exec.probePort }}
        resources:
          requests:
            cpu: {{ .Values.emailService.resources.requests.cpu }}
            memory: {{ .Values.emailService.resources.requests.memory }}
          limits:
            cpu: {{ .Values.emailService.resources.limits.cpu }}
            memory: {{ .Values.emailService.resources.limits.memory }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: server
          image: {{ printf "%s:%s" .Values.checkoutService.image.repository .Values.checkoutService.image.tag }}
          ports:
          - containerPort: {{ .Values.checkoutService.ports.containerPort }}
          readinessProbe:
            exec:
              command: {{ printf "[%q, \"-addr=:%v\"]" .Values.checkoutService.healthChecks.readinessProbe.exec.probeBinaryPath .Values.emailService.healthChecks.readinessProbe.exec.probePort }}
          livenessProbe:
            exec:
              command: {{ printf "[%q, \"-addr=:%v\"]" .Values.checkoutService.healthChecks.livenessProbe.exec.probeBinaryPath .Values.emailService.healthChecks.livenessProbe.exec.probePort }}
          resources:
            requests:
              cpu: {{ .Values.checkoutService.resources.requests.cpu }}
              memory: {{ .Values.checkoutService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.checkoutService.resources.limits.cpu }}
              memory: {{ .Values.checkoutService.resources.limits.memory }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      terminationGracePeriodSeconds: {{ .Values.recommendationService.terminationGracePeriodSeconds }}
      containers:
      - name: server
          image: {{ printf "%s:%s" .Values.recommendationService.image.repository .Values.recommendationService.image.tag }}
        ports:
        - containerPort: {{ .Values.recommendationService.ports.containerPort }}
        readinessProbe:
          periodSeconds: {{ .Values.recommendationService.healthChecks.readinessProbe.periodSeconds }}
          exec:
            command: {{ printf "[%q, \"-addr=:%v\"]" .Values.recommendationService.healthChecks.readinessProbe.exec.probeBinaryPath .Values.emailService.healthChecks.readinessProbe.exec.probePort }}
        livenessProbe:
          periodSeconds: {{ .Values.recommendationService.healthChecks.livenessProbe.periodSeconds }}
          exec:
            command: {{ printf "[%q, \"-addr=:%v\"]" .Values.recommendationService.healthChecks.livenessProbe.exec.probeBinaryPath .Values.emailService.healthChecks.livenessProbe.exec.probePort }}
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: {{ .Values.env.productCatalogServiceAddr }}
        resources:
            requests:
              cpu: {{ .Values.recommendationService.resources.requests.cpu }}
              memory: {{ .Values.recommendationService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.recommendationService.resources.limits.cpu }}
              memory: {{ .Values.recommendationService.resources.limits.memory }}