apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: {{ .Values.emailService.service.type }}
  selector:
    app: emailservice
  ports:
  - name: {{ .Values.emailService.service.name }}
    port: {{ .Values.emailService.service.port }}
    targetPort: {{ .Values.emailService.ports.containerPort }}